import type { ServiceTask, TaskCategory } from "@/types";

/**
 * The PMS schedule every vehicle is measured against. Intervals follow typical
 * manufacturer guidance for light commercial fleets; each item is due on
 * whichever limit — distance or elapsed time — arrives first.
 */
export const SERVICE_TASKS: ServiceTask[] = [
  {
    id: "oil-filter",
    name: "Engine oil & filter change",
    category: "engine",
    intervalKm: 5_000,
    intervalMonths: 6,
    estimatedCost: 3_200,
    estimatedHours: 1,
    critical: true,
  },
  {
    id: "tire-rotation",
    name: "Tire rotation & pressure check",
    category: "tires",
    intervalKm: 10_000,
    intervalMonths: 6,
    estimatedCost: 900,
    estimatedHours: 0.75,
    critical: false,
  },
  {
    id: "brake-inspection",
    name: "Brake pad & rotor inspection",
    category: "brakes",
    intervalKm: 15_000,
    intervalMonths: 12,
    estimatedCost: 1_800,
    estimatedHours: 1.5,
    critical: true,
  },
  {
    id: "air-filter",
    name: "Air filter replacement",
    category: "engine",
    intervalKm: 20_000,
    intervalMonths: 12,
    estimatedCost: 1_400,
    estimatedHours: 0.5,
    critical: false,
  },
  {
    id: "cabin-filter",
    name: "Cabin filter replacement",
    category: "body",
    intervalKm: 20_000,
    intervalMonths: 12,
    estimatedCost: 1_100,
    estimatedHours: 0.5,
    critical: false,
  },
  {
    id: "battery-check",
    name: "Battery & charging system test",
    category: "electrical",
    intervalKm: 20_000,
    intervalMonths: 12,
    estimatedCost: 750,
    estimatedHours: 0.5,
    critical: false,
  },
  {
    id: "wheel-alignment",
    name: "Wheel alignment & balancing",
    category: "tires",
    intervalKm: 25_000,
    intervalMonths: 18,
    estimatedCost: 2_400,
    estimatedHours: 1.5,
    critical: false,
  },
  {
    id: "brake-fluid",
    name: "Brake fluid flush",
    category: "brakes",
    intervalKm: 40_000,
    intervalMonths: 24,
    estimatedCost: 2_600,
    estimatedHours: 1.5,
    critical: true,
  },
  {
    id: "transmission-fluid",
    name: "Transmission fluid service",
    category: "drivetrain",
    intervalKm: 60_000,
    intervalMonths: 36,
    estimatedCost: 6_800,
    estimatedHours: 2.5,
    critical: true,
  },
  {
    id: "coolant-flush",
    name: "Coolant flush & thermostat check",
    category: "engine",
    intervalKm: 60_000,
    intervalMonths: 36,
    estimatedCost: 4_200,
    estimatedHours: 2,
    critical: true,
  },
  {
    id: "timing-belt",
    name: "Timing belt inspection",
    category: "engine",
    intervalKm: 90_000,
    intervalMonths: 60,
    estimatedCost: 12_500,
    estimatedHours: 5,
    critical: true,
  },
  {
    id: "safety-inspection",
    name: "Annual roadworthiness inspection",
    category: "safety",
    intervalKm: 30_000,
    intervalMonths: 12,
    estimatedCost: 1_800,
    estimatedHours: 2,
    critical: true,
  },
];

export const TASK_BY_ID = new Map(SERVICE_TASKS.map((task) => [task.id, task]));

export const CATEGORY_LABEL: Record<TaskCategory, string> = {
  engine: "Engine",
  drivetrain: "Drivetrain",
  brakes: "Brakes",
  tires: "Tires & wheels",
  electrical: "Electrical",
  safety: "Safety",
  body: "Body & interior",
};
